### ISSUE TITLE
Self-hosted build doesn't work (livekit server at .env)

### ISSUE THREAD

**Issue by alexander-potemkin** [vector-im/element-call#2220]
### Steps to reproduce

1. Where are you starting? What can you see?

Readme.md to build and start the service. Got Synapse server with auto-registration.
2. What do you click?

Start call.

3. More steps

Call doesn't start. JS console have an error `TypeError: undefined is not an object (evaluating 'Nn.get().livekit.livekit_service_url')`

My `.env` file in root folder looks like the following:

```
LIVEKIT_KEY="devkey"
LIVEKIT_SECRET="secret"
VITE_DEFAULT_HOMESERVER=https://mysub.mydomain.com/
```

#### What did you expect?

I expected to find a variable and a place to put it to point to livekit server.

#### What happened instead?

I have found a commit removing this variable (https://github.com/element-hq/element-call/commit/19e478f2a976acfb8d7bc247ac0be5d82f2a18d8) tried to put it back to the `.env`, but with no luck.

So, I guess, I'm missing something.

### Operating system

Ubuntu 22.04 

### Browser information

Safari, but I guess it's not important

### Will you send logs?

Yes

**Comment by robintown** [comment]
Hi, the LiveKit service URL needs to be set in your deployment's config.json - you can see the very basic documentation that we have for the config options here: https://github.com/element-hq/element-call/blob/livekit/src/config/ConfigOptions.ts

(We realize that pointing people to the code for figuring out what config options to set is not ideal, we would appreciate PRs improving our documentation!)

**Comment by alexander-potemkin** [comment]
@robintown , thank you! Code is Ok, I was confused about build time options.
Is that right, that `.env` is of no use then now?

**Comment by robintown** [comment]
We still use the `.env` file to set build-time options such as custom CSS that you might want to inject, but yes, for configuring how the application connects to LiveKit it's no longer used.

**Comment by alexander-potemkin** [comment]
Thank you!

**Comment by alexander-potemkin** [comment]
@robintown , apologies, and what about livekit secret values? Where do I specify them? I can't find an option at Config.ts on that...

**Comment by alexander-potemkin** [comment]
I'm sorry, I've just figured out there is a prebuild back-end... 🤦

I've already setup livekit separately, with caddy on top of it, etc, so I would rather incorporate a missing back-end piece, which is:

```
  auth-service:
    image: ghcr.io/element-hq/lk-jwt-service:latest-ci
    hostname: auth-server
    ports:
      - 8881:8080
    environment:
      - LIVEKIT_URL=ws://localhost:7880
      - LIVEKIT_KEY=devkey
      - LIVEKIT_SECRET=secret
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - lkbackend
```

Just wanted to clarify a few things, if you don't mind?

-1. Is `ws://localhost:7880` - is a hardcoded thing somewhere? Which service will be looking for it and how it will be looking?
-2. I'm using livekit's docker compose and it uses 'host' mode:
```
services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
  redis:
    image: redis:7-alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./redis.conf:/etc/redis.conf
```
And I'm then using caddy to route traffic - is it something could be done with `lk-jwt-service` service as well?
