### ISSUE TITLE
Unable to join meeting via invitation link

### ISSUE THREAD

**Issue by MomentQYC** [vector-im/element-call#2340]
### Steps to reproduce

1. Creating rooms and inviting people
2. Invitee joins the room

#### What did you expect?
Normal use
#### What happened instead?
It displays an error like this
```
MatrixError: [404] Unrecognized request https://(server)/_matrix/client/unstable/im.nheko.summary/rooms/(roomid)%3A(server)/summary
```

### Operating system

Debian 12

### Browser information

Edge 124

### Will you send logs?

No

**Comment by fkwp** [comment]
Can you pls provide further information. Is it a self hosted deployments or using matrix.org. In case of self hosted: Can you pls share your configuration of the full stack (SFU, JWT-Service, Element Web/Desktop)

**Comment by MomentQYC** [comment]
> Can you pls provide further information. Is it a self hosted deployments or using matrix.org. In case of self hosted: Can you pls share your configuration of the full stack (SFU, JWT-Service, Element Web/Desktop)

Synapse
```yaml
server_name: (server)
report_stats: false
pid_file: "/var/run/matrix-synapse.pid"
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false
database:
  name: psycopg2
  args:
    user: synapse_user
    password: (secret)
    database: synapse
    host: 127.0.0.1
    cp_min: 5
    cp_max: 10
macaroon_secret_key: (secret)
log_config: "/etc/matrix-synapse/log.yaml"
serve_server_wellknown: true
media_store_path: /var/lib/matrix-synapse/media
signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
trusted_key_servers: []
max_avatar_size: 2M
allowed_avatar_mimetypes: ["image/png", "image/jpeg", "image/gif", "image/webp"]
federation_client_minimum_tls_version: 1.2
max_upload_size: 3M
enable_registration: true
session_lifetime: 696h
track_appservice_user_ips: true
turn_uris: [(secret)]
turn_shared_secret: "(secret)"
turn_user_lifetime: 86400000
turn_allow_guests: True
redis:
    enabled: true
    host: 127.0.0.1
    port: 6379
    password: (secret)
enable_registration_without_verification: true
enable_media_repo: true
media_storage_providers:
- module: s3_storage_provider.S3StorageProviderBackend
  store_local: False
  store_remote: True
  store_synchronous: True
  config:
    bucket: element-call
    #bucket: hashi
    # All of the below options are optional, for use with non-AWS S3-like
    # services, or to specify access tokens here instead of some external method.
    region_name: (secret)
    #region_name: (secret)
    #endpoint_url: (secret)
    endpoint_url: (secret)
    access_key_id: (secret)
    #access_key_id: (secret)
    #secret_access_key: (secret)
    secret_access_key: (secret)

    # The object storage class used when uploading files to the bucket.
    # Default is STANDARD.
    #storage_class: "STANDARD_IA"

    # The maximum number of concurrent threads which will be used to connect
    # to S3. Each thread manages a single connection. Default is 40.
    #
    #threadpool_size: 20
forgotten_room_retention_period: 7d
media_retention:
    local_media_lifetime: 7d
    remote_media_lifetime: 3d

experimental:
    msc3266_enabled: true
```

SFU `livekit with default config`

JWT-Service
```
LIVEKIT_URL="ws://127.0.0.1:7880"
LIVEKIT_KEY=(secret)
LIVEKIT_SECRET=(secret)
```

Element-Call
```json
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "(server)",
            "server_name": "(server)"
        }
    },
    "livekit": {
        "livekit_service_url": "(JWT-Service)"
    }
}
```
