### ISSUE TITLE
Just a quick How To for building element-call on bare metal

### ISSUE THREAD

**Issue by escix** [vector-im/element-call#2750]
#### What would you like to do?
Inform others how I selfhosted element-call on FreeBSD

#### Why would you like to do it?
Helping others and learn from others if I did something wrong
#### How would you like to achieve it?
By posting the below instructions:

Caddyfile:
```
(matrix-well-known-header) {
    # Headers
    header Access-Control-Allow-Origin "*"
    header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
    header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    header Content-Type "application/json"
}


(logging) {
        log {
                level DEBUG
                output file /var/log/caddy/caddy.log {
                        roll_size 15mb
                        roll_keep 20
                }
        }
}

(errors) {
        handle_errors {
#                root * /DATA/worldweb/error_pages
                rewrite * /{http.error.status_code}.html
                file_server
        }
}

(server_add) {
        bind PUBLIC_IPV4
        bind PUBLIC_IPV6
}

turnserver.mydomain.com {
        import logging
        import errors
        import server_add

 }




mydomain.com {
        import logging
        import errors
        import server_add

        header /.well-known/matrix/* Content-Type application/json
        header /.well-known/matrix/* Access-Control-Allow-Origin *

        respond /.well-known/matrix/server {"m.server":"mydomain.com:443"}
        respond /.well-known/matrix/client {"m.homeserver":{"base_url":"https://mydomain.com"},"org.matrix.msc3575.proxy":{"url":"https://mydomain.com/sliding-sync"},"org.matrix.msc4143.rtc_foci":{"type":"livekit","livekit_service_url":"https://livekit-jwt.mydomain.com"}}
        respond /.well-known/element/element.json {"call":{"widget_url":"https://call.mydomain.com"}}

        handle /_matrix/client/unstable/org.matrix.msc3575/sync* {
        reverse_proxy unix//var/run/synapse/main_public.sock

        }
        reverse_proxy /_matrix/* unix//var/run/synapse/main_public.sock
        reverse_proxy /_synapse/client/* unix//var/run/synapse/main_public.sock
        reverse_proxy /_synapse/admin/* unix//var/run/synapse/main_public.sock

        handle_path /sliding-sync/* {
                reverse_proxy unix//var/run/synapse/main_public.sock

        }

    }

call.mydomain.com {
        import logging
        import server_add
        root * /opt/sliding_sync/element-call/dist
        file_server
        try_files {path} /index.html
}

livekit.mydomain.com {
        import logging
        import server_add
        reverse_proxy IP_OF_LIVEKIT:7880
}

livekit-jwt.mydomain.com {
        import logging
        import server_add
        reverse_proxy IP_OF_LK:8080
}
```

homeser.yaml:
```
experimental_features:
  msc3266_enabled: true

max_event_delay_duration: 24h

```
dits/config.json:

```
{
  "default_server_config":{
    "m.homeserver":{
      "base_url":"https://mydomain.com",
      "server_name":"mydomain.com"
    }
  },
  "livekit": {
    "livekit_service_url":"https://livekit-jwt.mydomain.com"
  },
  "element_call": {
     "url": "https://call.mydomain.com",
     "participant_limit": 8,
     "brand": "Element Call",
     "use_exclusively": true
    },
  "features":{
    "feature_video_rooms": true,
    "feature_new_room_decoration_ui": true,
    "feature_group_calls": true,
    "feature_element_call_video_rooms": true,
    "feature_use_device_session_member_events":true
  }
}
```

livekit.yaml:

```
port: 7880
bind_addresses:
  - "0.0.0.0"
log_level: info
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  # use_external_ip should be set to true for most cloud environments where
  # the host has a public IP address, but is not exposed to the process.
  # LiveKit will attempt to use STUN to discover the true IP, and advertise
  # that IP with its clients
  use_external_ip: true

  turn_servers:
  - host: turnserver.mydomain.com
    username: "Username"
    credential: "password"
    port: 3478
    protocol: tcp
  - host: turnserver.mydomain.com
    username: "Username"
    credential: "password"
    port: 5349
    protocol: tls
  - host: turnserver.mydomain.com
    username: "Username"
    credential: "password"
    port: 3478
    protocol: udp



turn:
  enabled: false

redis:

keys:
  devkey: secretcodefordevkey

room:
  enabled_codecs:
    - mime: video/h264
    - mime: audio/opus
```

Build element-call:
```
git clone https://github.com/element-hq/element-call.git
cd element-call
yarn
yarn build
```

Build livekit:
```
git clone https://github.com/livekit/livekit
cd livekit
./bootstrap.sh
mage
```

```
/opt/sliding_sync/livekit/livekit/bin/livekit-server --config /opt/sliding_sync/element-call/backend/livekit.yaml &
```

clone and run lk-jwt-service:
```
cd /opt/sliding_sync/lk-jwt-service/lk-jwt-service && HOMESERVER_URL="https://mydomain.com" LIVEKIT_URL="wss://livekit.mydomain.com" LIVEKIT_KEY=devkey LIVEKIT_SECRET=secretcodefordevkey go run *.go &
```
