### ISSUE TITLE
Proper usage instructions in README

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#589]
#### What would you like to do?
As EC grows up into a product people might use rather than just a experimental dev project, our README should say how to get it up & running rather than just how to set up a dev env. ie. ideally after https://github.com/vector-im/element-call/issues/588 the most prominent thing would probably be a link to the built tarball to unpack onto a web server. Then probably instructions to build & host yourself, then finally the dev instructions 

#### Why would you like to do it?
People are trying to host their own EC and getting very confused and trying to run the vite dev server in production and running into all sorts of problems.

**Comment by paulvt** [comment]
I tried to use the Docker image that is already published to the container repo with some `docker-compose` definition I came up with on my own:

```yaml
version: '3'

services:
  server:
    image: ghcr.io/vector-im/element-call:latest
    restart: unless-stopped
    environment:
      VITE_DEFAULT_HOMESERVER: "https://<matrix domain>"
    ports:
      - "127.0.0.1:8009:8080/tcp"
```

However, it seems that the environment is ignored? Element Call works fine but still wants to create accounts and call rooms on `call.ems.host`. I also tried providing `.env.example` as `.env` or providing a modified `vite.config.js`, but those solutions also didn't work.

Is stuff still too hardcoded yet to make this work?
