### ISSUE TITLE
You are not invited to this room

### ISSUE THREAD

**Issue by MomentQYC** [vector-im/element-call#824]
### Steps to reproduce

1. Use a new synapse server
2. Create an account and log in/Access as a guest
3. Create and enter a room/enter a room

#### What did you expect?
Normal use

#### What happened instead?
Either after logging into the account or after access as a guest, it says
```
MatrixError: [403] You are not invited to this room.
```

##### Homeserver config file
```yaml
# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
#
# This is set in /etc/matrix-synapse/conf.d/server_name.yaml for Debian installations.
server_name: *
pid_file: "/var/run/matrix-synapse.pid"
serve_server_wellknown: true
report_stats: false
suppress_key_server_warning: true
macaroon_secret_key: *
form_secret: *
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false
  
database:
  name: psycopg2
  args:
    user: *
    password: *
    database: *
    host: *
    cp_min: 5
    cp_max: 10
log_config: "/etc/matrix-synapse/log.yaml"
media_store_path: /var/lib/matrix-synapse/media
signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
trusted_key_servers: []
max_avatar_size: 5M
allowed_avatar_mimetypes: ["image/png", "image/jpeg", "image/gif", "image/webp"]
federation_client_minimum_tls_version: 1.2
max_upload_size: 5M
enable_registration: true
turn_uris: [* ]
turn_shared_secret: "*"
turn_allow_guests: True

redis:
    enabled: true
    host: *
    port: *
    password: *
registration_shared_secret: *

enable_registration_without_verification: true

```

### Operating system

Zorin OS 16.2 Pro (Ubuntu 20.04)

### Browser information

Edge 108

### URL for webapp

Dec. 24, 2022 Clone from GitHub

### Will you send logs?

No
